services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: '1'
      MSSQL_SA_PASSWORD: '&tC7v}nd92-prtG+YT[_97{_ELK6Gt]+B+O,m]#+=3r-42&kgs'
    ports:
      - '1433:1433'
    volumes:
      - sql-data:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  sql-data:
